server:
  port: 8088
spring:
  application:
    name: micro-student
eureka:
  client:
    service-url:
      #配置eureka的注册地址
      #defaultZone没有提示，必须手写
      defaultZone: http://localhost:20000/eureka